### ISSUE TITLE
Less Player Details

### ISSUE THREAD

**Issue by Arnaud-Burn** [Yoshi20/LuxSmash#18]
Delete those players options to avoid GDPR issues
- Mobile number
- Gender
- birth date

It's too difficult to manage those sensitives data without a correct DPO, and because I think they are not that relevant for our goal.

**Comment by Yoshi20** [comment]
I don't think this is an issue since those data are optionally. No one have to give them if they don't want to.
With the last checkbox in the registration, they were also informed about and have to agree on this.

If your adamant about it, I can hide those fields, but I think it would be quite a loss for the statistics (players overview).

**Comment by Arnaud-Burn** [comment]
Ok, so up to now, we can leave them on; if I receive a complain about them, I'll come back.

So case close for now
