### ISSUE TITLE
Into the "Canton" section, Add other countries

### ISSUE THREAD

**Issue by Arnaud-Burn** [Yoshi20/LuxSmash#24]
Hi Yomi !

![image](https://user-images.githubusercontent.com/7067777/207835132-31f196ad-f610-4d48-a779-d03d333f1fe8.png)

For the "canton" section", would that be possible to add others ?
- Belgium
- France
- Germany
- Others

Thats a reccuring question that we received :)

Thank you

**Comment by Yoshi20** [comment]
"Others" can not be added (no coat of arms).
(Since Cantons is not a mandatory field, it can be left empty for "Others")

I was a little hesitant to add france and germany since they have a site for their own.
Since all sites are using the same database (to prevent gamertag conflicts etc.) it could lead to some confusion.
Let me know if there's a problem.
